name: Contiuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  build:
    name: Build, lint, and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update
      - name: Build
        run: cargo build --verbose --workspace
      - name: Check formatting
        run: cargo fmt --verbose --all -- --check
      - name: Run clippy
        run: cargo clippy --verbose --workspace
      - name: Run tests
        run: cargo test --verbose --workspace

  spelling:
    name: Spell checking
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@v1.29.9
